### ISSUE TITLE
Enemy

### ISSUE THREAD

**Issue by pintjuk** [pintjuk/MineTD#1]
Make an enemy that can be render, updated, will resive a path an will folow it.

**Comment by mk4** [comment]
ja alltså... vad hände med batch.begin(); ... batch.end();

**Comment by pintjuk** [comment]
jag behöver ha det här klart nu så jag tar över det själv. kontakta mig när du vill ha en annan upgift

**Comment by mk4** [comment]
sorry, det har inte framgått
jag är klar med de andra kurserna nu (utom matten)
ser väl om jag kan göra något annat under tiden

**Comment by pintjuk** [comment]
skulle du kunna titta på hur scene2d fungerar och se om du kan göra ett gui
för spelet med en panel där man kan välja material att byga och litte andra
grejer som kan vara bra att ha

Den 7 maj 2013 11:22 skrev mk4 notifications@github.com:
